version: "3.8"

services:
  # 1. Database Service
  db:
    image: postgres:15-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mystery122
      POSTGRES_DB: library-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # This line auto-creates your tables on startup!
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Node.js App Service
  app:
    build: .
    container_name: library_api
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_USER=postgres
      - DB_PASSWORD=mystery122
      - DB_NAME=library-db
      - DB_HOST=db # Points to the service name above
      - DB_PORT=5432
      - JWT_SECRET=secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
